### ISSUE TITLE
STDERR redirected too opened file

### ISSUE THREAD

**Issue by lim-daniel** [matsumotory/mruby-redis#55]
# What is wrong?

When I load file and save it, then rest of system commands STDERR is redirected to that file. It appear **only, when I have redis instance inside code.**

Example:

```
box_txt = File.read( '/example.txt' )
redis = Redis.new '127.0.0.1', 6379

File.open( '/example.txt', 'w' ) { |file|
  file.write( box_txt )
}

`echo 'test echo 1'`
`echo 'test echo 2' 1>&2`
```

This code should do nothing special, but it add string "test echo 2" to file.

**Comment by franckverrot** [comment]
@lim-daniel Are you using a specific gem to implement backquotes in mruby as [it's not implemented by default](https://github.com/mruby/mruby/blob/master/mrblib/kernel.rb#L11)?

**Comment by lim-daniel** [comment]
mattn/mruby-xquote :)

**Comment by franckverrot** [comment]
Thanks, I went ahead and used `mruby-io` to implement `File` operations.

Here's my config:
```ruby
  conf.gem :github => 'iij/mruby-io'
  conf.gem :github => 'mattn/mruby-xquote'
```

Sadly, I can't reproduce what you're describing with that setup. Anything special in your config? Mind pasting your config?

Thanks!

**Comment by lim-daniel** [comment]
Whole config used in project, with bug

```ruby
MRuby::Build.new do |conf|
  toolchain :gcc
  enable_debug
  conf.gembox 'full-core'

  conf.cc do |cc|
    cc.flags.push('-fomit-frame-pointer')
  end

  conf.gem github: 'matsumoto-r/mruby-redis'
  conf.gem github: 'iij/mruby-io'
  conf.gem github: 'iij/mruby-regexp-pcre'
  conf.gem github: 'matsumoto-r/mruby-sleep'
  conf.gem github: 'AndrewBelt/mruby-yaml'
  conf.gem github: 'mattn/mruby-xquote'
  conf.gem github: 'mattn/mruby-json'
  conf.gem github: 'iij/mruby-syslog'
  conf.gem github: 'iij/mruby-process'
end
```

**Comment by franckverrot** [comment]
Hi there,

I tried with all those gems and I still can't reproduce. 😞 

I noticed `mruby-io` there and [it's implementing backquotes](https://github.com/iij/mruby-io/blob/master/mrblib/kernel.rb#L3) too, maybe it's colliding with another gem?

**Comment by lim-daniel** [comment]
At this moment I just created simple workaround 
```ruby
`echo 'some string' > /example.txt.tmp`
`echo 'secondline' >> /example.txt.tmp`
`echo 'last line' >> /example.txt.tmp`
`mv /example.txt.tmp /example.txt`
```
Maybe it's mruby-io and mruby-xquote thanks for pointing it out :)
Btw I use latest master of mruby, maybe there was some changes in this case. Same as on mruby master mruby-regexp-pcre don't work properly at this moment, but few month ago it worked like a charm.
