### ISSUE TITLE
C99 style 'for' loop initial declarations

### ISSUE THREAD

**Issue by yyamano** [matsumotory/mruby-redis#62]
The latest version of mrb_redis.c uses C99 style 'for' loop initial declarations.

It makes ngx_mruby with BUILD_DYNAMIC_MODULE build fails. See https://travis-ci.org/matsumoto-r/ngx_mruby/jobs/152663915 and https://travis-ci.org/matsumoto-r/ngx_mruby/jobs/152663918

I guess you don't like C99 style because @sawanoboly fixed similar problems. 54a1ea0fa0146224e4e09ad1261fc467c36db7e8 4ce9a22fb2d0b3526a015b337ae54386f3de7ce7 0642e5d1889bff8a52413df4695eae4887f279d7

**Comment by yyamano** [comment]
Also I don't think 4ce9a22fb2d0b3526a015b337ae54386f3de7ce7 and 0642e5d1889bff8a52413df4695eae4887f279d7 are right fixes. There are multiple declarations with different types.

**Comment by matsumotory** [comment]
Already refactored.
