### ISSUE TITLE
Add Redis#setnx

### ISSUE THREAD

**Issue by coffeesam** [matsumotory/mruby-redis#86]
This is a very good redis command to have. Hope you will consider:
https://redis.io/commands/setnx

**Comment by franckverrot** [comment]
@coffeesam `SETNX` got added. Mind checking if that's OK for you? Thanks!

**Comment by franckverrot** [comment]
@matsumotory Mind closing this one? Thanks!

**Comment by matsumotory** [comment]
Thanksz
