### ISSUE TITLE
Return reply instead of self

### ISSUE THREAD

**Issue by tmshn** [matsumotory/mruby-redis#89]
## Background

Currentry, `set` method returns self, so there's no way to see errors or nil reply:

```ruby
> r = Redis.new HOST, PORT
 => #<Redis:0x123456>
> r.set "foo", "bar"
 => #<Redis:0x123456>
> r.get "foo"
 => "bar"
> r.set "foo", "not bar", "NX" => true
 => #<Redis:0x123456> # <- can't know if succeeded
> r.get "foo"
 => "bar"
```

Not only `set` but there area several methods that returns self. This might lead to the problem or insufficient functionality.

Here's the list of methods that return self.

| Method                                       | Reply                  | Is this a problem?                                                  |
|:---------------------------------------------|:-----------------------|:--------------------------------------------------------------------|
| [`auth`](https://redis.io/commands/auth`)    | 'OK' or error          |               No (error reply is handled well).                                   |
| [`select`](https://redis.io/commands/select) | 'OK'                   |               Perhaps (error reply is not handled, but may not occure?).          |
| [`set`](https://redis.io/commands/set`)      | 'OK' or nil            | :exclamation: Yes (can't distinguish OK and nil, and error reply is not handled). |
| [`del`](https://redis.io/commands/del`)      | Integer                | :exclamation: Yes (can't get number of deleted).                                  |
| [`hmset`](https://redis.io/commands/hmset`)  | 'OK'                   |               No (error reply is handled well).                                   |
| [`mset`](https://redis.io/commands/mset`)    | 'OK'                   |               No (error reply is handled well).                                   |
| [`zadd`](https://redis.io/commands/zadd`)    | Integer or bulk string | :exclamation: Yes (can't get number of added, or new scores).                     |

## My proposal

Let's change these methods to return reply (not the all, but at least marked with exclamation).

I know this breaks api compatibility, so want to hear from others before starting implementation.

I hope few people bounds returned client and uses it...

**Comment by matsumotory** [comment]
looks good. Could you send me the PR?

**Comment by tmshn** [comment]
Ok, I'll start working on this soon (currently working on different one).

**Comment by matsumotory** [comment]
Wow! Great!

**Comment by franckverrot** [comment]
Great, we might even be able to rework how we test those methods (like doing a `get` after `set` to ensure `set` worked properly?)

**Comment by tmshn** [comment]
@matsumotory @franckverrot 

My work is here 👉 #91 
As you see, the changes are so big...sorry ☹️

**Comment by matsumotory** [comment]
@tmshn OK, I can understand the PR.
