### ISSUE TITLE
Issue is compilation

### ISSUE THREAD

**Issue by gaukhush** [matsumotory/mruby-redis#95]
Hi @matsumotory 

When we make the  nginx bit, it is giving us the error . Can you please help to fix.

ngx_mruby/mruby/build/mrbgems/mruby-redis/src/mrb_redis.c:333:9: error: wrong type argument to unary exclamation mark
     if (!mrb_hash_empty_p(mrb, opt)) {
         ^

**Comment by matsumotory** [comment]
mruby-redis supports master branch of mruby. So, you should update mruby to master.

**Comment by gaukhush** [comment]
Thanks @matsumotory

**Comment by matsumotory** [comment]
You are welcome!

**Comment by gaukhush** [comment]
Hi @matsumotory 

When try to execute ngx_mruby it fails as build_mruby failed, attached below error for reference. Can you please help here to fix this.

build: [exec] git clone git://github.com/redis/hiredis.git
Cloning into 'hiredis'...
build: [exec] make
make[1]: Entering directory '/usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis'
gcc -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -fPIC -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb net.c
gcc -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -fPIC -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb hiredis.c
hiredis.c: In function 'redisCommand':
hiredis.c:999:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     void *reply = redisvCommand(c,format,ap);
     ^
gcc -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -fPIC -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb sds.c
sds.c: In function 'sdsnewlen':
sds.c:88:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     int hdrlen = sdsHdrSize(type);
     ^
gcc -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -fPIC -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb async.c
async.c: In function 'callbackValDup':
async.c:71:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     redisCallback *dup = malloc(sizeof(*dup));
     ^
async.c: In function '__redisAsyncCopyError':
async.c:148:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     redisContext *c = &(ac->c);
     ^
gcc -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -fPIC -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb read.c
gcc -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -fPIC -shared -Wl,-soname,libhiredis.so.0.14 -o libhiredis.so  net.o hiredis.o sds.o async.o read.o
ar rcs libhiredis.a net.o hiredis.o sds.o async.o read.o
gcc -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -fPIC -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb test.c
test.c: In function 'test_format_commands':
test.c:210:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     const char *argv[3];
     ^
test.c:214:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     size_t lens[3] = { 3, 7, 3 };
     ^
test.c:229:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     sds sds_cmd;
     ^
test.c: In function 'test_blocking_io_errors':
test.c:645:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     struct timeval tv = { 0, 1000 };
     ^
gcc -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -fPIC -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb -o hiredis-test  test.o libhiredis.a
Generating hiredis.pc for pkgconfig...
make[1]: Leaving directory '/usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis'
build: [exec] make install
make[1]: Entering directory '/usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis'
mkdir -p /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/include/hiredis /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/include/hiredis/adapters /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/lib
cp -pPR hiredis.h async.h read.h sds.h /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/include/hiredis
cp -pPR adapters/*.h /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/include/hiredis/adapters
cp -pPR libhiredis.so /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/lib/libhiredis.so.0.14
cd /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/lib && ln -sf libhiredis.so.0.14 libhiredis.so
cp -pPR libhiredis.a /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/lib
mkdir -p /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/lib/pkgconfig
cp -pPR hiredis.pc /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/lib/pkgconfig
make[1]: Leaving directory '/usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis'
build: [exec] git clone git://github.com/symisc/vedis.git
Cloning into 'vedis'...
GIT   https://github.com/ksss/mruby-stringio.git -> build/mrbgems/mruby-stringio
Cloning into '/usr/local/shopmatic/ngx_mruby/mruby/build/mrbgems/mruby-stringio'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 13 (delta 0), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (13/13), done.
Checking connectivity... done.
GIT   https://github.com/matsumotory/mruby-pointer.git -> build/mrbgems/mruby-pointer
Cloning into '/usr/local/shopmatic/ngx_mruby/mruby/build/mrbgems/mruby-pointer'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 19 (delta 2), reused 14 (delta 1), pack-reused 0
Unpacking objects: 100% (19/19), done.
Checking connectivity... done.
rake aborted!
Can't find /usr/local/shopmatic/ngx_mruby/mruby/mrbgems/mruby-metaprog/mrbgem.rake
/usr/local/shopmatic/ngx_mruby/mruby/tasks/mruby_build_gem.rake:28:in `gem'
/usr/local/shopmatic/ngx_mruby/mruby/tasks/mrbgem_spec.rake:346:in `generate_gem_table'
/usr/local/shopmatic/ngx_mruby/mruby/tasks/mrbgem_spec.rake:420:in `check'
/usr/local/shopmatic/ngx_mruby/mruby/tasks/mrbgems.rake:5:in `block in <top (required)>'
/usr/local/shopmatic/ngx_mruby/mruby/tasks/mruby_build.rake:13:in `instance_eval'
/usr/local/shopmatic/ngx_mruby/mruby/tasks/mruby_build.rake:13:in `block in each_target'
/usr/local/shopmatic/ngx_mruby/mruby/tasks/mruby_build.rake:12:in `each'
/usr/local/shopmatic/ngx_mruby/mruby/tasks/mruby_build.rake:12:in `each_target'
/usr/local/shopmatic/ngx_mruby/mruby/tasks/mrbgems.rake:1:in `<top (required)>'
/usr/local/shopmatic/ngx_mruby/mruby/Rakefile:26:in `load'
/usr/local/shopmatic/ngx_mruby/mruby/Rakefile:26:in `<top (required)>'
(See full trace by running task with --trace)
Makefile:78: recipe for target 'build_mruby' failed
make: *** [build_mruby] Error 1
