### ISSUE TITLE
rescue section for 'Redis::ConnectionError' swallows other exceptions

### ISSUE THREAD

**Issue by shiftky** [matsumotory/mruby-redis#97]
I encountered a problem with exception handling of mruby-redis's errors.

In the following case, it is expected to show `"rescued ProtocolError"` if a `Redis::ProtocolError` raised. But it is handled in `rescue Redis::ConnectionError` section.

```ruby
begin
  raise Redis::ProtocolError
rescue Redis::ConnectionError
  p "rescued ConnectoinError"
rescue Redis::ProtocolError
  p "rescued ProtocolError"
end

# => "rescued ConnectoinError"
```

This problem will not occur depending on the order of rescue sections. It is expected result if you set `Redis::ProtocolError` to the top rescue section.

```ruby
begin
  raise Redis::ProtocolError
rescue Redis::ProtocolError
  p "rescued ProtocolError"
rescue Redis::ConnectionError
  p "rescued ConnectoinError"
end

# => "rescued ProtocolError"
```

`Redis::ProtocolError` is subclass of `Redis::ConnectionError`. Therefore `raise Redis::ConnectionError` section will swallow every single exception.

**Comment by matsumotory** [comment]
@shiftky Thank you for your report. It's BUG, and I will fix this.
